### PR TITLE
restore 1.4.0 version

### PR DESCRIPTION
**Pull request by motobob**
a version of 1.4.0 I had on may laptop...

### CODE REVIEW

**Comment by motobob** [comment]
test it

**Comment by smilerlee** [comment]
@motobob  Seems your version is a little different from @goodgoblin's and mine.

**Comment by motobob** [comment]
@smilerlee okay then...please PR your version to see the diff as i believe your version is better.

**Comment by smilerlee** [comment]
@motobob I've pushed to tag `1.4.0` just now. It's identical to @goodgoblin's. please check if there's something wrong.

**Comment by motobob** [comment]
interesting... https://github.com/erlcloud/lhttpc/compare/1.4.0...talko_1.4.0

**Comment by smilerlee** [comment]
@motobob you need to fetch to your local repo and use `git diff`, the difference is just the README file, not that big.
my copy was checked out on Nov. 10 (to our server), and the tag was created on May 20, 2014.  @goodgoblin checked out recently, it's identical to mine.

**Comment by smilerlee** [comment]
I recommend we just force update the `master` branch to tag `1.4.0`, which should be the same with one historical (or maybe the latest) state of repo `talko/lhttpc`.

**Comment by smilerlee** [comment]
Seems it's the best way. I'll force update the `master` branch.

**Pull request closed without merging**
